name: watchlist
description: A new Flutter project.
publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  bloc: ^7.0.0
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter:
    sdk: flutter
  get_it: ^7.1.3
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  injectable: ^1.4.1
  intl: ^0.17.0
  path_provider: ^2.0.2

dev_dependencies:
  build_runner: 2.0.4
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  injectable_generator: ^1.4.1
  lint: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat_Regular.ttf
        - asset: assets/fonts/Montserrat_Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat_Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat_ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat_Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat_Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat_ExtraLight.ttf
          weight: 200
